name: monitoring_tool
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.14.0
  latlong2: ^0.8.0
  flutter_riverpod: ^1.0.1
  http: ^0.13.3
  drift: ^1.0.1
  cupertino_icons: ^1.0.2
  sqlite3_flutter_libs: ^0.5.0
  fl_chart: ^0.41.0
  intl: ^0.17.0
  csv: ^5.0.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1
  file_picker: ^4.6.1
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  build_runner:
  drift_dev: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - cbs_logo.png

