name: desktop
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  latlong2: ^0.8.0
  flutter_riverpod: ^1.0.1
  http: ^0.13.3
  intl: 0.17.0
  drift: ^1.0.1
  cupertino_icons: ^1.0.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  uuid: ^3.0.5
  csv: ^5.0.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1
  fl_chart: ^0.45.0
  charts_flutter: ^0.12.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  drift_dev: ^1.0.2
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true